# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f2d765345aa354a25894852fa68f705b6e39d039443804d7f21b6c287fe2baa22a6433213d01edc5e28a1013cb8ac492d31d1e310c29be8f22834010835ba65

test:
  secret_key_base: 6e94d9e6c7d6349bf8d20df0361428250bc029e9a0bf36fa2966913574d1d8ab2689f5ea393c2ee634766b82170d019e67708867b16a86877856a50baf348206

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
